<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<authors>Folkehelseinstituttet (FHI)</authors>
	<Copyright>(c) 2022-2025 Folkehelseinstituttet (FHI)</Copyright>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	<projectUrl>https://github.com/folkehelseinstituttet/Fhi.Slash.Mottak</projectUrl>
	<RepositoryUrl>https://github.com/folkehelseinstituttet/Fhi.Slash.Mottak</RepositoryUrl>
	<PackageDescription>The client program simplifies interaction with the API by handling encryption, signing, and HelseID authentication automatically. It allows organizations to seamlessly send healthcare data while adhering to security and compliance requirements.</PackageDescription>
	<PackageReadmeFile>readme.md</PackageReadmeFile>
	<PackageIcon>fhi.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup>
	<!-- We have chosen not to use primary constructors for this project. -->
	<NoWarn>IDE0290</NoWarn>
  </PropertyGroup>
	
  <PropertyGroup>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\readme.md" Pack="true" PackagePath="\" />
	<None Include="docs\fhi.png" Pack="true" PackagePath="\" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="IdentityModel" Version="6.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.1" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
	<PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

</Project>
