<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestFiles\Client\helseid-client-definition.json" />
    <None Remove="TestFiles\Client\test_cert_without_password.pfx" />
    <None Remove="TestFiles\Client\test_cert_without_password_2.pfx" />
    <None Remove="TestFiles\HelseId\access-token.txt" />
    <None Remove="TestFiles\HelseId\pub-key-set.json" />
    <None Remove="TestFiles\Slash\priv-key.pem" />
    <None Remove="TestFiles\Slash\pub-key.pem" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="TestFiles\Client\helseid-client-definition.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\Client\empty_message.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\Client\test_cert_without_password.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\Client\test_cert_without_password_2.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\HelseId\access-token.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\HelseId\pub-key-set.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\Slash\priv-key.pem">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\Slash\pub-key.pem">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
	  <PackageReference Include="MSTest" Version="3.8.3" />
	  <PackageReference Include="WireMock.Net" Version="1.7.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fhi.Slash.Public.SlashMessengerCLI\Fhi.Slash.Public.SlashMessengerCLI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
